config:
  ==: SuperElytraConfig # If you change this line, the plugin may not load properly.
  chargeup-ticks: 60 # How many ticks it takes to launch from the ground.
  speed-multiplier: 1.0 # How much to increase the flying speed each tick.
  launch-multiplier: 1.0 # How much to increase the boost amount.
  default: true # If flight/boosting should be enabled by default.
  charge-sound: FUSE
  ready-sound: BAT_TAKEOFF
  launch-sound: ENDERDRAGON_WINGS
  autosave-interval: 600 # Saves player preferences in this second interval.
  cooldown: 50 # Cooldown on launching in miliseconds.
  # Set the max angle that a player can boost at.
  # Above horizontal is negative, below horizontal is positive
  max-glide-angle: -90.0
  # Apply additional boosting to fireworks
  boost-enabled: true
  # Additional boost per boost tick
  boost-modifier: 1.0
  # Ticks per firework duration level
  boost-duration: 20
  # Allows infinitely boosting with the sneak key
  allow-crouch-boost: false
  worlds:
    - world
  world-blacklist: false
