name: SuperElytra
main: eisenwave.elytra.SuperElytraPlugin
version: @version@
api-version: 1.13

permissions:
  superelytra.glide:
    description: "enhanced gliding"
    default: true
  superelytra.launch:
    description: "launch by sneaking"
    default: true
  superelytra.command.elytramode:
    description: "/elytramode"
    default: true
  superelytra.command.elytrareload:
    description: "/elytrareload"
    default: op
  superelytra.command.elytraprefs:
    description: "/elytraprefs"
    default: true

commands:
  elytrareload:
    aliases: [elreload]
    permission: superelytra.command.elytrareload
    description: "Reloads the SuperElytra plugin."
  elytraprefs:
    aliases: [elprefs, elytrapreferences]
    permission: superelytra.command.elytraprefs
    description: "Changes user preferences."
  elytramode:
    aliases: [elmode]
    permission: superelytra.command.elytramode
    description: "changes the personal elytra mode"
